version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - Maintenance
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    labels:
      - Maintenance
    schedule:
      interval: monthly
