name: checks
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: main
jobs:
  should_skip_check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.skip.outputs.should_skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: outdated_runs
          paths_ignore: '["license", "**.md", "**.code-workspace"]'
  check:
    needs: should_skip_check
    if: ${{ needs.should_skip_check.outputs.result != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: yarn
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          scope: spear-ai
      - run: |
          yarn install
          yarn run check
          yarn run build
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
