name: commitlint
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          scope: spear-ai
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: .commitlintrc.json
