name: commitlint
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .node-version
      - run: yarn install
      - uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: .commitlintrc.json
