name: publish
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .node-version
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - run: |
          yarn install
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
