name: release
on:
  push:
    branches: main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: false
  git-tag:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ needs.release.outputs.major }} || true
          git tag -d v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }} || true
          git tag -d v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }} || true
          git push origin :v${{ needs.release.outputs.major }} || true
          git push origin :v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }} || true
          git push origin :v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }} || true
          git tag -a v${{ needs.release.outputs.major }} -m "Release v${{ needs.release.outputs.major }}"
          git tag -a v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }} -m "Release v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}"
          git tag -a v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }} -m "Release v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }}"
          git push origin v${{ needs.release.outputs.major }}
          git push origin v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}
          git push origin v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}.${{ needs.release.outputs.patch }}
  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: .node-version
          registry-url: https://npm.pkg.github.com
      - run: |
          yarn install
          yarn run build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
      - run: |
          yarn install
          yarn run build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
